### ISSUE TITLE
Functions other than data frame

### ISSUE THREAD

**Issue by verynewtocode** [zinccat/ace_tools_open#1]
Here is the list of tools OpenAI offer

I see a data frame function. Well done

what about others

STDOUT/STDERR
Help on package ace_tools:

NAME
    ace_tools

PACKAGE CONTENTS

FUNCTIONS
    display_chart_to_user(path: str, title: str, chart_type: str) -> None
    
    display_dataframe_to_user(name: str, dataframe: pandas.core.frame.DataFrame) -> pandas.core.frame.DataFrame
    
    display_matplotlib_image_to_user(title: str, reason: str, exception_ids: list[str]) -> None
    
    log_exception(message: str, exception_id: str | None = None, func_name: str | None = None, args: list[typing.Any] | None = None, kwargs: dict[str, typing.Any] | None = None) -> None
    
    log_matplotlib_img_fallback(reason: str, metadata: dict[str, typing.Any] | None = None) -> None

FILE
    /home/sandbox/.local/lib/python3.11/site-packages/ace_tools/__init__.py

**Comment by zinccat** [comment]
hi, thanks for the issue, can you share some examples of these functions, e.g., the conversation history?

**Comment by verynewtocode** [comment]
Here is all the runnable code combined in one block for generating and displaying Intel's revenue chart:

```python
import matplotlib.pyplot as plt
import ace_tools as tools
import pandas as pd

# Data for Intel's revenue from 2020 to 2023
years = [2020, 2021, 2022, 2023]
revenue = [77.87, 79.02, 63.05, 54.23]  # in billion USD

# Creating a DataFrame for the data
data = {
    "Year": years,
    "Revenue (Billion USD)": revenue
}

df = pd.DataFrame(data)

# Displaying the DataFrame to the user using ace_tools
tools.display_dataframe_to_user(name="Intel Corporation Annual Revenue", dataframe=df)

# Saving the plot to a file
chart_path = "/mnt/data/intel_revenue_chart.png"

plt.figure(figsize=(10, 6))
plt.plot(years, revenue, marker='o', linestyle='-', color='b')

# Adding titles and labels
plt.title('Intel Corporation Annual Revenue (2020-2023)', fontsize=14)
plt.xlabel('Year', fontsize=12)
plt.ylabel('Revenue (Billion USD)', fontsize=12)

# Saving the chart as a PNG file
plt.grid(True)
plt.savefig(chart_path)

# Using ace_tools to display the chart
tools.display_chart_to_user(path=chart_path, title="Intel Revenue Trend (2020-2023)", chart_type="line")
```

This code will generate and display Intel's annual revenue chart from 2020 to 2023, as well as show the corresponding data in table format.

**Comment by verynewtocode** [comment]
import matplotlib.pyplot as plt
import ace_tools as tools

# Data for Intel number of employees over the years (example data)
years = [2018, 2019, 2020, 2021, 2022, 2023]
employees = [107100, 110800, 110600, 121100, 131900, 133900]

# Plotting the chart
plt.figure(figsize=(10, 6))
plt.plot(years, employees, marker='o', linestyle='-', color='b')

# Adding title and labels
plt.title('Intel Number of Employees Over the Years')
plt.xlabel('Year')
plt.ylabel('Number of Employees')

# Display the chart using the ace_tools function
tools.display_matplotlib_image_to_user(
    title="Intel Number of Employees Over the Years",
    reason="Visualization of employee trends from 2018 to 2023",
    exception_ids=[]
)

**Comment by zinccat** [comment]
Thank you! I'll work on this, should be similar to plt.show()

**Comment by zinccat** [comment]
fixed

**Comment by verynewtocode** [comment]
Well done and thank you so much
